"""
Virtual Memory: Paging, Segmentation, Page Tables, TLB, and Page Faults

A self-contained study and simulation program that progresses from the
fundamentals of virtual memory to multi-level page tables, segmentation,
TLB behavior, page faults, replacement policies, and performance analysis.

Run:
    python virtual_memory.py
"""

from __future__ import annotations

from collections import OrderedDict, deque
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple
import random


# ============================================================================
# SECTION 1: FUNDAMENTAL TERMINOLOGY
# ============================================================================

def print_section(title: str) -> None:
    print("\n" + "=" * 78)
    print(title)
    print("=" * 78)


def explain_basic_terms() -> None:
    print_section("1. Virtual Memory Fundamentals")

    terms = {
        "Virtual address": (
            "An address generated by a CPU for a process. It belongs to the "
            "process's virtual address space rather than directly identifying RAM."
        ),
        "Physical address": (
            "An address identifying a location in physical main memory (RAM)."
        ),
        "Page": (
            "A fixed-size block of virtual memory. A common educational size is "
            "4096 bytes, or 4 KiB."
        ),
        "Frame": (
            "A fixed-size block of physical memory. Its size equals the page size."
        ),
        "Page table": (
            "A data structure used to translate virtual page numbers into physical "
            "frame numbers."
        ),
        "TLB": (
            "Translation Lookaside Buffer. A small, fast cache of recent virtual-"
            "page-to-physical-frame translations."
        ),
        "Page fault": (
            "An exception raised when a referenced virtual page is not currently "
            "resident in an appropriate physical frame."
        ),
        "Segmentation": (
            "A memory-management model in which a process is divided into logical "
            "variable-sized segments such as code, data, stack, and heap."
        ),
    }

    for name, description in terms.items():
        print(f"{name:20}: {description}")

    print("\nCore distinction:")
    print("  Virtual memory is an abstraction.")
    print("  Paging provides fixed-size allocation and translation.")
    print("  Segmentation models logical variable-sized regions.")
    print("  The TLB accelerates address translation.")
    print("  A page fault transfers control to the operating system.")


# ============================================================================
# SECTION 2: ADDRESS CALCULATIONS
# ============================================================================

def calculate_page_components(
    virtual_address: int,
    page_size: int,
    virtual_address_bits: int,
) -> Tuple[int, int, int]:
    """Return page number, offset, and maximum virtual address."""
    if page_size <= 0 or page_size & (page_size - 1):
        raise ValueError("Page size must be a positive power of two.")

    if virtual_address < 0:
        raise ValueError("Virtual address cannot be negative.")

    maximum_address = (1 << virtual_address_bits) - 1

    if virtual_address > maximum_address:
        raise ValueError("Virtual address exceeds the configured address space.")

    page_number = virtual_address // page_size
    offset = virtual_address % page_size
    return page_number, offset, maximum_address


def demonstrate_address_translation_math() -> None:
    print_section("2. Virtual Address Decomposition")

    page_size = 4096
    virtual_address_bits = 16
    virtual_address = 0x3A7B

    page_number, offset, maximum = calculate_page_components(
        virtual_address,
        page_size,
        virtual_address_bits,
    )

    print(f"Virtual address : 0x{virtual_address:04X}")
    print(f"Page size       : {page_size} bytes")
    print(f"Page number     : {page_number}")
    print(f"Offset          : {offset}")
    print(f"Maximum address : 0x{maximum:04X}")

    offset_bits = page_size.bit_length() - 1
    page_bits = virtual_address_bits - offset_bits

    print(f"Offset bits     : {offset_bits}")
    print(f"Page-number bits: {page_bits}")

    print("\nFor a power-of-two page size:")
    print("  page number = virtual_address >> offset_bits")
    print("  offset      = virtual_address & (page_size - 1)")


# ============================================================================
# SECTION 3: SIMPLE PAGE TABLE
# ============================================================================

@dataclass
class PageTableEntry:
    frame_number: Optional[int] = None
    present: bool = False
    writable: bool = True
    executable: bool = False
    user_accessible: bool = True
    referenced: bool = False
    dirty: bool = False


class SimplePageTable:
    """A basic single-level page table."""

    def __init__(self, virtual_pages: int, physical_frames: int):
        if virtual_pages <= 0 or physical_frames <= 0:
            raise ValueError("Memory sizes must be positive.")

        self.entries = [PageTableEntry() for _ in range(virtual_pages)]
        self.physical_frames = physical_frames
        self.free_frames = deque(range(physical_frames))

    def map_page(
        self,
        page_number: int,
        writable: bool = True,
        executable: bool = False,
    ) -> int:
        self._validate_page(page_number)

        entry = self.entries[page_number]

        if entry.present:
            return entry.frame_number  # type: ignore

        if not self.free_frames:
            raise MemoryError("No physical frames are available.")

        frame = self.free_frames.popleft()

        entry.frame_number = frame
        entry.present = True
        entry.writable = writable
        entry.executable = executable

        return frame

    def unmap_page(self, page_number: int) -> None:
        self._validate_page(page_number)

        entry = self.entries[page_number]

        if entry.present and entry.frame_number is not None:
            self.free_frames.append(entry.frame_number)

        self.entries[page_number] = PageTableEntry()

    def translate(self, page_number: int, offset: int, page_size: int) -> int:
        self._validate_page(page_number)

        if not 0 <= offset < page_size:
            raise ValueError("Offset is outside the page.")

        entry = self.entries[page_number]

        if not entry.present or entry.frame_number is None:
            raise PageFault(page_number)

        entry.referenced = True
        return entry.frame_number * page_size + offset

    def _validate_page(self, page_number: int) -> None:
        if not 0 <= page_number < len(self.entries):
            raise ValueError("Virtual page number is outside the page table.")


class PageFault(Exception):
    """Exception representing a simulated page fault."""

    def __init__(self, page_number: int):
        super().__init__(f"Page fault on virtual page {page_number}")
        self.page_number = page_number


def demonstrate_single_level_page_table() -> None:
    print_section("3. Single-Level Page Table")

    page_size = 256
    table = SimplePageTable(virtual_pages=8, physical_frames=4)

    table.map_page(0, writable=False, executable=True)
    table.map_page(2, writable=True)
    table.map_page(5, writable=True)

    for page_number, entry in enumerate(table.entries):
        if entry.present:
            print(
                f"VPN {page_number:2} -> PFN {entry.frame_number:2} | "
                f"present={entry.present} | writable={entry.writable} | "
                f"executable={entry.executable}"
            )

    try:
        physical_address = table.translate(2, 17, page_size)
        print(f"\nVirtual page 2, offset 17 -> physical address {physical_address}")
    except PageFault as fault:
        print(fault)

    try:
        table.translate(4, 0, page_size)
    except PageFault as fault:
        print(f"Expected exception: {fault}")


# ============================================================================
# SECTION 4: TLB
# ============================================================================

@dataclass
class TLBEntry:
    frame_number: int
    writable: bool
    executable: bool


class TLB:
    """
    Small LRU translation cache.

    Real hardware TLBs are implemented in specialized hardware, but this
    OrderedDict model makes the replacement behavior easy to study.
    """

    def __init__(self, capacity: int):
        if capacity <= 0:
            raise ValueError("TLB capacity must be positive.")

        self.capacity = capacity
        self.entries: OrderedDict[int, TLBEntry] = OrderedDict()
        self.hits = 0
        self.misses = 0

    def lookup(self, page_number: int) -> Optional[TLBEntry]:
        entry = self.entries.get(page_number)

        if entry is None:
            self.misses += 1
            return None

        self.hits += 1
        self.entries.move_to_end(page_number)
        return entry

    def insert(self, page_number: int, entry: TLBEntry) -> None:
        self.entries[page_number] = entry
        self.entries.move_to_end(page_number)

        if len(self.entries) > self.capacity:
            self.entries.popitem(last=False)

    def invalidate(self, page_number: Optional[int] = None) -> None:
        if page_number is None:
            self.entries.clear()
        else:
            self.entries.pop(page_number, None)

    @property
    def hit_rate(self) -> float:
        total = self.hits + self.misses
        return self.hits / total if total else 0.0


def demonstrate_tlb() -> None:
    print_section("4. Translation Lookaside Buffer")

    tlb = TLB(capacity=2)

    translations = {
        1: TLBEntry(8, True, False),
        2: TLBEntry(3, True, False),
        3: TLBEntry(9, False, True),
    }

    for page_number in [1, 2, 1, 3, 1, 2]:
        result = tlb.lookup(page_number)

        if result:
            print(f"VPN {page_number}: TLB HIT -> frame {result.frame_number}")
        else:
            print(f"VPN {page_number}: TLB MISS")
            tlb.insert(page_number, translations[page_number])

    print(f"TLB hits   : {tlb.hits}")
    print(f"TLB misses : {tlb.misses}")
    print(f"Hit rate   : {tlb.hit_rate:.2%}")


# ============================================================================
# SECTION 5: PAGED MEMORY SYSTEM
# ============================================================================

@dataclass
class Frame:
    frame_number: int
    page_number: Optional[int] = None
    process_id: Optional[int] = None
    dirty: bool = False
    referenced: bool = False


@dataclass
class AccessResult:
    virtual_address: int
    physical_address: Optional[int]
    page_number: int
    offset: int
    tlb_hit: bool
    page_fault: bool
    evicted_page: Optional[int]
    message: str


class PagedMemorySystem:
    """
    Integrated virtual-memory simulator.

    It models:
      - virtual pages
      - physical frames
      - a page table
      - a TLB
      - page faults
      - FIFO/LRU page replacement
      - dirty pages
      - access permissions
    """

    def __init__(
        self,
        virtual_pages: int,
        physical_frames: int,
        page_size: int = 256,
        tlb_capacity: int = 4,
        replacement_policy: str = "LRU",
    ):
        if virtual_pages <= 0:
            raise ValueError("virtual_pages must be positive.")
        if physical_frames <= 0:
            raise ValueError("physical_frames must be positive.")
        if page_size <= 0 or page_size & (page_size - 1):
            raise ValueError("page_size must be a power of two.")

        policy = replacement_policy.upper()

        if policy not in {"FIFO", "LRU", "CLOCK"}:
            raise ValueError("Replacement policy must be FIFO, LRU, or CLOCK.")

        self.virtual_pages = virtual_pages
        self.physical_frames = physical_frames
        self.page_size = page_size
        self.replacement_policy = policy

        self.page_table: Dict[int, PageTableEntry] = {
            page: PageTableEntry() for page in range(virtual_pages)
        }

        self.frames = [Frame(i) for i in range(physical_frames)]
        self.tlb = TLB(tlb_capacity)

        self.fifo_queue: deque[int] = deque()
        self.lru_order: OrderedDict[int, None] = OrderedDict()
        self.clock_hand = 0

        self.page_faults = 0
        self.memory_accesses = 0
        self.disk_reads = 0
        self.disk_writes = 0

    def access(
        self,
        virtual_address: int,
        write: bool = False,
        execute: bool = False,
    ) -> AccessResult:
        self.memory_accesses += 1

        page_number = virtual_address // self.page_size
        offset = virtual_address % self.page_size

        if not 0 <= page_number < self.virtual_pages:
            raise ValueError("Virtual address is outside the process address space.")

        tlb_entry = self.tlb.lookup(page_number)

        if tlb_entry is not None:
            if write and not tlb_entry.writable:
                raise PermissionError("Write access denied by TLB permissions.")
            if execute and not tlb_entry.executable:
                raise PermissionError("Execution denied by TLB permissions.")

            frame_number = tlb_entry.frame_number
            self._mark_frame_used(frame_number)
            return AccessResult(
                virtual_address,
                frame_number * self.page_size + offset,
                page_number,
                offset,
                True,
                False,
                None,
                "TLB hit",
            )

        page_entry = self.page_table[page_number]

        if not page_entry.present:
            self.page_faults += 1
            evicted_page = self._handle_page_fault(page_number)
            page_entry = self.page_table[page_number]

            self.tlb.insert(
                page_number,
                TLBEntry(
                    page_entry.frame_number,  # type: ignore
                    page_entry.writable,
                    page_entry.executable,
                ),
            )

            if write:
                page_entry.dirty = True

            if execute and not page_entry.executable:
                raise PermissionError("Execution denied by page table.")

            physical_address = (
                page_entry.frame_number * self.page_size + offset  # type: ignore
            )

            return AccessResult(
                virtual_address,
                physical_address,
                page_number,
                offset,
                False,
                True,
                evicted_page,
                "Page fault handled and translation installed",
            )

        if write and not page_entry.writable:
            raise PermissionError("Write access denied by page table.")

        if execute and not page_entry.executable:
            raise PermissionError("Execution denied by page table.")

        page_entry.referenced = True

        if write:
            page_entry.dirty = True

        frame_number = page_entry.frame_number
        self.tlb.insert(
            page_number,
            TLBEntry(
                frame_number,  # type: ignore
                page_entry.writable,
                page_entry.executable,
            ),
        )

        self._mark_frame_used(frame_number)  # type: ignore

        return AccessResult(
            virtual_address,
            frame_number * self.page_size + offset,  # type: ignore
            page_number,
            offset,
            False,
            False,
            None,
            "Page-table translation",
        )

    def _handle_page_fault(self, page_number: int) -> Optional[int]:
        free_frame = next(
            (frame for frame in self.frames if frame.page_number is None),
            None,
        )

        if free_frame is not None:
            frame = free_frame
            evicted_page = None
        else:
            frame = self._choose_victim()
            evicted_page = frame.page_number

            if evicted_page is not None:
                victim_entry = self.page_table[evicted_page]

                if victim_entry.dirty:
                    self.disk_writes += 1

                victim_entry.present = False
                victim_entry.frame_number = None
                victim_entry.dirty = False
                victim_entry.referenced = False

                self.tlb.invalidate(evicted_page)
                self.lru_order.pop(evicted_page, None)

        self.disk_reads += 1

        frame.page_number = page_number
        frame.dirty = False
        frame.referenced = True

        entry = self.page_table[page_number]
        entry.present = True
        entry.frame_number = frame.frame_number
        entry.referenced = True
        entry.dirty = False

        self.fifo_queue.append(frame.frame_number)
        self.lru_order[page_number] = None

        return evicted_page

    def _choose_victim(self) -> Frame:
        if self.replacement_policy == "FIFO":
            frame_number = self.fifo_queue.popleft()
            return self.frames[frame_number]

        if self.replacement_policy == "LRU":
            victim_page, _ = self.lru_order.popitem(last=False)
            frame_number = self.page_table[victim_page].frame_number
            if frame_number is None:
                raise RuntimeError("LRU metadata is inconsistent.")
            return self.frames[frame_number]

        # CLOCK / second-chance replacement.
        while True:
            frame = self.frames[self.clock_hand]

            if not frame.referenced:
                self.clock_hand = (self.clock_hand + 1) % len(self.frames)
                return frame

            frame.referenced = False

            if frame.page_number is not None:
                self.page_table[frame.page_number].referenced = False

            self.clock_hand = (self.clock_hand + 1) % len(self.frames)

    def _mark_frame_used(self, frame_number: int) -> None:
        frame = self.frames[frame_number]
        frame.referenced = True

        if frame.page_number is None:
            return

        page_number = frame.page_number

        if self.replacement_policy == "LRU":
            self.lru_order.pop(page_number, None)
            self.lru_order[page_number] = None

        self.page_table[page_number].referenced = True

    def print_state(self) -> None:
        print("\nPage table:")
        for page in range(self.virtual_pages):
            entry = self.page_table[page]
            if entry.present:
                print(
                    f"  VPN {page:2} -> frame {entry.frame_number:2} | "
                    f"dirty={entry.dirty} referenced={entry.referenced}"
                )
            else:
                print(f"  VPN {page:2} -> not resident")

        print("\nPhysical frames:")
        for frame in self.frames:
            print(
                f"  Frame {frame.frame_number:2}: "
                f"VPN={frame.page_number} dirty={frame.dirty} "
                f"referenced={frame.referenced}"
            )

    def statistics(self) -> Dict[str, float]:
        accesses = self.memory_accesses

        return {
            "memory_accesses": accesses,
            "page_faults": self.page_faults,
            "page_fault_rate": self.page_faults / accesses if accesses else 0.0,
            "tlb_hits": self.tlb.hits,
            "tlb_misses": self.tlb.misses,
            "tlb_hit_rate": self.tlb.hit_rate,
            "disk_reads": self.disk_reads,
            "disk_writes": self.disk_writes,
        }


def demonstrate_integrated_paging() -> None:
    print_section("5. Integrated Paging System")

    system = PagedMemorySystem(
        virtual_pages=8,
        physical_frames=3,
        page_size=256,
        tlb_capacity=2,
        replacement_policy="LRU",
    )

    addresses = [
        (10, False),
        (266, False),
        (522, True),
        (10, False),
        (778, False),
        (266, False),
        (522, True),
        (1030, False),
    ]

    for address, write in addresses:
        try:
            result = system.access(address, write=write)
            print(
                f"VA={address:4} VPN={result.page_number} "
                f"offset={result.offset:3} "
                f"PA={result.physical_address:4} "
                f"TLB={'HIT' if result.tlb_hit else 'MISS'} "
                f"fault={'YES' if result.page_fault else 'NO '} "
                f"evicted={result.evicted_page} "
                f"({result.message})"
            )
        except (ValueError, PermissionError) as error:
            print(f"Access VA={address}: ERROR: {error}")

    system.print_state()

    print("\nStatistics:")
    for name, value in system.statistics().items():
        if isinstance(value, float):
            print(f"  {name:18}: {value:.2%}" if "rate" in name else f"  {name:18}: {value:.3f}")
        else:
            print(f"  {name:18}: {value}")


# ============================================================================
# SECTION 6: SEGMENTATION
# ============================================================================

@dataclass
class Segment:
    name: str
    base: int
    limit: int
    readable: bool = True
    writable: bool = False
    executable: bool = False

    def translate(self, offset: int, write: bool = False, execute: bool = False) -> int:
        if offset < 0 or offset >= self.limit:
            raise MemoryError(
                f"Segmentation fault: offset {offset} exceeds segment '{self.name}'."
            )

        if write and not self.writable:
            raise PermissionError(
                f"Write denied for segment '{self.name}'."
            )

        if execute and not self.executable:
            raise PermissionError(
                f"Execution denied for segment '{self.name}'."
            )

        return self.base + offset


class SegmentedMemory:
    """Simple logical-address to physical-address segmentation model."""

    def __init__(self):
        self.segments: Dict[int, Segment] = {}

    def add_segment(self, selector: int, segment: Segment) -> None:
        if selector < 0:
            raise ValueError("Segment selector cannot be negative.")
        self.segments[selector] = segment

    def translate(
        self,
        selector: int,
        offset: int,
        write: bool = False,
        execute: bool = False,
    ) -> int:
        if selector not in self.segments:
            raise MemoryError("Invalid segment selector.")

        return self.segments[selector].translate(offset, write, execute)


def demonstrate_segmentation() -> None:
    print_section("6. Segmentation")

    memory = SegmentedMemory()

    memory.add_segment(
        1,
        Segment(
            name="code",
            base=10000,
            limit=2000,
            readable=True,
            writable=False,
            executable=True,
        ),
    )

    memory.add_segment(
        2,
        Segment(
            name="data",
            base=20000,
            limit=3000,
            readable=True,
            writable=True,
            executable=False,
        ),
    )

    memory.add_segment(
        3,
        Segment(
            name="stack",
            base=30000,
            limit=1000,
            readable=True,
            writable=True,
            executable=False,
        ),
    )

    print("Code offset 120 ->", memory.translate(1, 120, execute=True))
    print("Data offset 500 ->", memory.translate(2, 500, write=True))

    try:
        memory.translate(1, 120, write=True)
    except PermissionError as error:
        print("Expected protection error:", error)

    try:
        memory.translate(3, 1001)
    except MemoryError as error:
        print("Expected bounds error:", error)


# ============================================================================
# SECTION 7: PAGING VERSUS SEGMENTATION
# ============================================================================

def compare_paging_and_segmentation() -> None:
    print_section("7. Paging Versus Segmentation")

    comparison = [
        ("Allocation unit", "Fixed-size page", "Variable-size segment"),
        ("Primary idea", "Physical placement efficiency", "Logical program organization"),
        ("Fragmentation", "Internal fragmentation possible", "External fragmentation possible"),
        ("Address form", "Page number + offset", "Segment selector + offset"),
        ("Protection", "Page-level permissions", "Natural logical-region protection"),
        ("Sharing", "Page-based sharing", "Logical-region sharing"),
        ("Typical modern use", "Core mechanism in general-purpose VMs", "Often combined with paging or used conceptually"),
    ]

    print(f"{'Property':25} | {'Paging':32} | Segmentation")
    print("-" * 90)

    for row in comparison:
        print(f"{row[0]:25} | {row[1]:32} | {row[2]}")


# ============================================================================
# SECTION 8: MULTI-LEVEL PAGE TABLES
# ============================================================================

class TwoLevelPageTable:
    """
    Simplified two-level page table.

    A virtual page number is split into:
        directory index + table index.

    This avoids allocating one large contiguous table when much of the
    virtual address space is unused.
    """

    def __init__(self, directory_entries: int, table_entries: int):
        if directory_entries <= 0 or table_entries <= 0:
            raise ValueError("Page-table dimensions must be positive.")

        self.directory: Dict[int, Dict[int, int]] = {}
        self.directory_entries = directory_entries
        self.table_entries = table_entries

    def map_page(self, virtual_page: int, frame: int) -> None:
        directory_index = virtual_page // self.table_entries
        table_index = virtual_page % self.table_entries

        if not 0 <= directory_index < self.directory_entries:
            raise ValueError("Virtual page is outside the two-level structure.")

        table = self.directory.setdefault(directory_index, {})
        table[table_index] = frame

    def translate(self, virtual_page: int) -> Optional[int]:
        directory_index = virtual_page // self.table_entries
        table_index = virtual_page % self.table_entries

        table = self.directory.get(directory_index)

        if table is None:
            return None

        return table.get(table_index)


def demonstrate_multilevel_page_tables() -> None:
    print_section("8. Multi-Level Page Tables")

    table = TwoLevelPageTable(directory_entries=4, table_entries=4)

    table.map_page(0, 10)
    table.map_page(1, 11)
    table.map_page(8, 20)
    table.map_page(15, 27)

    for virtual_page in [0, 1, 2, 8, 15]:
        frame = table.translate(virtual_page)
        print(f"Virtual page {virtual_page:2} -> frame {frame}")

    print(
        "\nOnly directory entries that contain mappings need lower-level "
        "page tables in this simplified sparse representation."
    )


# ============================================================================
# SECTION 9: EFFECTIVE MEMORY ACCESS TIME
# ============================================================================

def effective_access_time(
    memory_time_ns: float,
    tlb_time_ns: float,
    tlb_hit_rate: float,
) -> float:
    """
    Simplified EAT assuming:
        TLB lookup + one memory access on a TLB hit
        TLB lookup + two memory accesses on a TLB miss

    This model intentionally ignores caches and pipeline overlap.
    """
    if memory_time_ns < 0 or tlb_time_ns < 0:
        raise ValueError("Times cannot be negative.")

    if not 0 <= tlb_hit_rate <= 1:
        raise ValueError("TLB hit rate must be between 0 and 1.")

    hit_cost = tlb_time_ns + memory_time_ns
    miss_cost = tlb_time_ns + 2 * memory_time_ns

    return tlb_hit_rate * hit_cost + (1 - tlb_hit_rate) * miss_cost


def demonstrate_eat() -> None:
    print_section("9. Effective Access Time")

    memory_time = 100
    tlb_time = 10

    for hit_rate in [0.50, 0.80, 0.95, 0.99]:
        eat = effective_access_time(memory_time, tlb_time, hit_rate)
        print(f"TLB hit rate {hit_rate:5.0%} -> EAT {eat:.1f} ns")

    print(
        "\nA real CPU has additional hierarchy effects such as L1/L2/L3 caches, "
        "page-walk caches, speculative execution, and hardware page walkers."
    )


# ============================================================================
# SECTION 10: PAGE REPLACEMENT ALGORITHMS
# ============================================================================

def fifo_page_faults(reference_string: List[int], frame_count: int) -> int:
    """Classic FIFO page-replacement simulation."""
    if frame_count <= 0:
        raise ValueError("Frame count must be positive.")

    frames: List[int] = []
    queue: deque[int] = deque()
    faults = 0

    for page in reference_string:
        if page in frames:
            continue

        faults += 1

        if len(frames) < frame_count:
            frames.append(page)
            queue.append(page)
        else:
            victim = queue.popleft()
            frames[frames.index(victim)] = page
            queue.append(page)

    return faults


def lru_page_faults(reference_string: List[int], frame_count: int) -> int:
    """LRU replacement based on most-recently-used order."""
    if frame_count <= 0:
        raise ValueError("Frame count must be positive.")

    frames: OrderedDict[int, None] = OrderedDict()
    faults = 0

    for page in reference_string:
        if page in frames:
            frames.move_to_end(page)
            continue

        faults += 1

        if len(frames) == frame_count:
            frames.popitem(last=False)

        frames[page] = None

    return faults


def optimal_page_faults(reference_string: List[int], frame_count: int) -> int:
    """
    The theoretical optimal algorithm.

    It replaces the page whose next use is farthest in the future.
    Real operating systems cannot know the future exactly, so this is mainly
    a comparison baseline.
    """
    if frame_count <= 0:
        raise ValueError("Frame count must be positive.")

    frames: List[int] = []
    faults = 0

    for index, page in enumerate(reference_string):
        if page in frames:
            continue

        faults += 1

        if len(frames) < frame_count:
            frames.append(page)
            continue

        future = reference_string[index + 1:]
        distances = []

        for resident in frames:
            try:
                distance = future.index(resident)
            except ValueError:
                distance = float("inf")
            distances.append(distance)

        victim_index = distances.index(max(distances))
        frames[victim_index] = page

    return faults


def demonstrate_replacement_algorithms() -> None:
    print_section("10. Page Replacement Algorithms")

    reference_string = [7, 0, 1, 2, 0, 3, 0, 4, 2, 3, 0, 3, 2]

    print("Reference string:", reference_string)

    for frames in [2, 3, 4]:
        fifo = fifo_page_faults(reference_string, frames)
        lru = lru_page_faults(reference_string, frames)
        optimal = optimal_page_faults(reference_string, frames)

        print(
            f"Frames={frames}: "
            f"FIFO faults={fifo}, "
            f"LRU faults={lru}, "
            f"Optimal faults={optimal}"
        )

    print(
        "\nImportant distinction: the TLB replacement policy and the physical-page "
        "replacement policy solve different caching problems."
    )


# ============================================================================
# SECTION 11: THRASHING AND WORKING SET
# ============================================================================

def working_set(reference_string: List[int], window_size: int) -> List[int]:
    """Return the number of distinct pages in each sliding window."""
    if window_size <= 0:
        raise ValueError("Window size must be positive.")

    result = []

    for end in range(len(reference_string)):
        start = max(0, end - window_size + 1)
        result.append(len(set(reference_string[start:end + 1])))

    return result


def demonstrate_working_set() -> None:
    print_section("11. Working Set and Thrashing")

    locality_heavy = [1, 2, 1, 2, 1, 2, 1, 2, 3, 2, 1, 2]
    locality_poor = list(range(12))

    for name, sequence in [
        ("Locality-heavy", locality_heavy),
        ("Locality-poor", locality_poor),
    ]:
        sizes = working_set(sequence, window_size=4)
        print(f"{name:16}: {sequence}")
        print(f"{' ' * 16} Working-set sizes: {sizes}")

    print(
        "\nThrashing occurs when a system spends excessive time servicing page "
        "faults and moving pages rather than performing useful computation."
    )
    print(
        "Working-set and page-fault-frequency ideas help operating systems detect "
        "or control memory pressure."
    )


# ============================================================================
# SECTION 12: COPY-ON-WRITE
# ============================================================================

@dataclass
class SharedPage:
    frame_number: int
    reference_count: int = 1


class CopyOnWriteManager:
    """
    Small conceptual simulation of copy-on-write.

    Parent and child initially reference the same physical frame. A write by
    either process causes a private copy when the page is shared.
    """

    def __init__(self):
        self.next_frame = 0
        self.pages: Dict[Tuple[str, int], SharedPage] = {}

    def allocate(self, process: str, virtual_page: int) -> None:
        frame = self.next_frame
        self.next_frame += 1
        self.pages[(process, virtual_page)] = SharedPage(frame)

    def fork_share(
        self,
        parent: str,
        child: str,
        virtual_page: int,
    ) -> None:
        parent_key = (parent, virtual_page)

        if parent_key not in self.pages:
            raise ValueError("Parent page does not exist.")

        shared = self.pages[parent_key]
        shared.reference_count += 1
        self.pages[(child, virtual_page)] = shared

    def write(self, process: str, virtual_page: int) -> int:
        key = (process, virtual_page)

        if key not in self.pages:
            raise ValueError("Process page does not exist.")

        page = self.pages[key]

        if page.reference_count > 1:
            page.reference_count -= 1

            new_page = SharedPage(self.next_frame)
            self.next_frame += 1

            self.pages[key] = new_page
            page = new_page

        return page.frame_number


def demonstrate_copy_on_write() -> None:
    print_section("12. Copy-on-Write")

    manager = CopyOnWriteManager()
    manager.allocate("parent", 0)
    manager.fork_share("parent", "child", 0)

    print(
        "Before child write:",
        "parent frame =", manager.pages[("parent", 0)].frame_number,
        "child frame =", manager.pages[("child", 0)].frame_number,
    )

    manager.write("child", 0)

    print(
        "After child write:",
        "parent frame =", manager.pages[("parent", 0)].frame_number,
        "child frame =", manager.pages[("child", 0)].frame_number,
    )

    print(
        "The physical frame is shared until a write requires private state."
    )


# ============================================================================
# SECTION 13: ADDRESS-SPACE SECURITY
# ============================================================================

def demonstrate_memory_protection() -> None:
    print_section("13. Memory Protection and Security")

    table = SimplePageTable(virtual_pages=4, physical_frames=4)

    table.map_page(0, writable=False, executable=True)
    table.map_page(1, writable=True, executable=False)

    code_page = table.entries[0]
    data_page = table.entries[1]

    print(
        f"Code page: writable={code_page.writable}, "
        f"executable={code_page.executable}"
    )
    print(
        f"Data page: writable={data_page.writable}, "
        f"executable={data_page.executable}"
    )

    print(
        "\nImportant security principles include least privilege, page-level "
        "permissions, user/kernel isolation, ASLR, and W^X-style policies."
    )

    print(
        "A page-table permission check is only one layer of a modern system's "
        "security architecture."
    )


# ============================================================================
# SECTION 14: EDGE CASES
# ============================================================================

def demonstrate_edge_cases() -> None:
    print_section("14. Edge Cases and Failure Conditions")

    cases = [
        ("negative address", lambda: calculate_page_components(-1, 4096, 16)),
        ("non-power-of-two page size", lambda: calculate_page_components(100, 3000, 16)),
        ("address outside address space", lambda: calculate_page_components(70000, 4096, 16)),
        ("zero TLB capacity", lambda: TLB(0)),
        ("invalid segment", lambda: SegmentedMemory().translate(99, 0)),
    ]

    for name, operation in cases:
        try:
            operation()
            print(f"{name}: unexpectedly succeeded")
        except (ValueError, MemoryError, PermissionError) as error:
            print(f"{name}: correctly rejected -> {error}")


# ============================================================================
# SECTION 15: PERFORMANCE AND DESIGN TRADE-OFFS
# ============================================================================

def print_performance_considerations() -> None:
    print_section("15. Performance and Design Considerations")

    points = [
        "Larger pages reduce page-table overhead but can increase internal fragmentation.",
        "Smaller pages can improve granularity but increase translation metadata.",
        "A larger TLB can improve coverage but consumes scarce fast hardware resources.",
        "Multi-level tables save space for sparse address spaces but require more translation steps on misses.",
        "Huge pages can reduce TLB pressure for large contiguous workloads.",
        "Page faults are vastly more expensive than ordinary memory accesses.",
        "Locality of reference strongly affects paging and TLB effectiveness.",
        "Dirty-page eviction can require a write-back to secondary storage.",
        "LRU is conceptually useful but exact hardware LRU can be expensive.",
        "Clock and related approximations trade exactness for lower implementation cost.",
    ]

    for point in points:
        print(" -", point)


# ============================================================================
# SECTION 16: TESTING
# ============================================================================

def run_self_tests() -> None:
    print_section("16. Self-Tests")

    page, offset, _ = calculate_page_components(5000, 4096, 16)
    assert page == 1
    assert offset == 904

    table = SimplePageTable(4, 2)
    frame = table.map_page(1)
    assert table.translate(1, 20, 256) == frame * 256 + 20

    try:
        table.translate(2, 0, 256)
    except PageFault:
        pass
    else:
        raise AssertionError("Expected a page fault.")

    assert fifo_page_faults([1, 2, 1, 3], 2) == 3
    assert lru_page_faults([1, 2, 1, 3], 2) == 3

    segment = Segment(
        name="test",
        base=100,
        limit=50,
        writable=True,
    )

    assert segment.translate(10, write=True) == 110

    try:
        segment.translate(50)
    except MemoryError:
        pass
    else:
        raise AssertionError("Expected segment bounds failure.")

    print("All self-tests passed.")


# ============================================================================
# SECTION 17: END-TO-END DEMONSTRATION
# ============================================================================

def run_access_trace_demo() -> None:
    print_section("17. End-to-End Access Trace")

    system = PagedMemorySystem(
        virtual_pages=16,
        physical_frames=4,
        page_size=1024,
        tlb_capacity=3,
        replacement_policy="CLOCK",
    )

    random.seed(42)

    trace = [
        random.choice([0, 1, 2, 3, 4, 5]) * 1024 + random.randrange(0, 1024)
        for _ in range(20)
    ]

    print("Generated virtual-address trace:")

    for address in trace:
        result = system.access(address)
        print(
            f"VA={address:5} -> PA={result.physical_address:5} | "
            f"VPN={result.page_number:2} | "
            f"TLB={'H' if result.tlb_hit else 'M'} | "
            f"PF={'Y' if result.page_fault else 'N'}"
        )

    stats = system.statistics()

    print("\nTrace statistics:")
    print(f"  Accesses    : {stats['memory_accesses']}")
    print(f"  TLB hit rate: {stats['tlb_hit_rate']:.2%}")
    print(f"  Page faults : {stats['page_faults']}")
    print(f"  Fault rate  : {stats['page_fault_rate']:.2%}")


# ============================================================================
# SECTION 18: MAIN PROGRAM
# ============================================================================

def main() -> None:
    explain_basic_terms()
    demonstrate_address_translation_math()
    demonstrate_single_level_page_table()
    demonstrate_tlb()
    demonstrate_integrated_paging()
    demonstrate_segmentation()
    compare_paging_and_segmentation()
    demonstrate_multilevel_page_tables()
    demonstrate_eat()
    demonstrate_replacement_algorithms()
    demonstrate_working_set()
    demonstrate_copy_on_write()
    demonstrate_memory_protection()
    demonstrate_edge_cases()
    print_performance_considerations()
    run_self_tests()
    run_access_trace_demo()

    print_section("Study Checklist")
    checklist = [
        "Virtual versus physical addresses",
        "Pages and frames",
        "Page-number and offset decomposition",
        "Page-table entries",
        "Present/valid and protection bits",
        "Single-level page tables",
        "Multi-level page tables",
        "TLB hits and misses",
        "Page faults",
        "Demand paging",
        "Page replacement",
        "FIFO, LRU, CLOCK, and optimal replacement",
        "Segmentation and segment protection",
        "Fragmentation",
        "Working sets and thrashing",
        "Copy-on-write",
        "Memory protection",
        "Effective access time",
        "Performance and security trade-offs",
    ]

    for item in checklist:
        print(f"  [x] {item}")


if __name__ == "__main__":
    main()
